#!/bin/bash
# 测试修复：验证 apriltag → block_align → grasp 流程

echo "====== 测试流程修复 ======"
echo ""
echo "1. 启动所有节点（除了 abcd_task）"
echo "   在一个终端运行："
echo "   ros2 launch abcd_task abcd_task.launch.py &"
echo ""
echo "2. 等待 grasp_task 进入 STANDBY 状态"
echo "   应该看到：grasp_task 节点已初始化，等待 /grasp/start 信号"
echo ""
echo "3. 触发 apriltag_place1："
echo "   ros2 topic pub --once /apriltag_place1/start std_msgs/msg/Bool \"data: true\""
echo ""
echo "4. 观察日志，应该看到："
echo "   - apriltag_place1_node: 发布 /apriltag_place1/done = True (不发 /grasp/start，由 block_align 接管)"
echo "   - grasp_task: 仍然在 STANDBY 状态（没有被提前触发）"
echo ""
echo "5. 启动 block_align（带颜色参数）："
echo "   ros2 run block_align block_align_node --ros-args --params-file ~/2026YuYaoGuoSai/lite3_ws/install/block_align/share/block_align/config/block_align.yaml -p target_color:=red &"
echo ""
echo "6. 触发 block_align："
echo "   ros2 topic pub --once /block_align/start std_msgs/msg/Bool \"data: true\""
echo ""
echo "7. 观察日志，应该看到："
echo "   - block_align_node: BlockDetection 目标颜色过滤: red"
echo "   - block_align_node: 开始检测（只检测红色）"
echo "   - 如果没有色块：进入横向搜索 'search 步 1/10'"
echo "   - block_align_node: 发布 /grasp/start = True (触发 grasp_task 抓取)"
echo "   - grasp_task: state -> DETECTING"
echo ""
echo "====== 验证要点 ======"
echo "✓ apriltag 完成后 grasp_task 没有被触发（仍在 STANDBY）"
echo "✓ block_align 显示目标颜色过滤"
echo "✓ block_align 完成后才触发 grasp_task"
echo "✓ 没有摄像头资源竞争错误"
echo "✓ 横向搜索功能可以执行"
